# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

on: [push]

jobs:
  services-test-job:
    runs-on: ubuntu-latest
    container: ubuntu-latest
#     services:
#       vitess1202:
#         image: wanghy1995/vtdriver-env:latest
#         options: >-
#           --health-cmd "mysqladmin ping -h127.0.0.1 -P17100 -uvtdriver -pvtdriver_password"
#           --health-interval 20s
#           --health-timeout 5s
#           --health-retries 5
#         env:
#           ONE_SHARD_ONLY: true
#           HOST_IP: 127.0.0.1
#           NO_VTGATE: true
#         ports:
#           - 17100:17100

    services:
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: mysql
#         ports:
#           # Opens tcp port 3306 on the host and service container
#           - 3306:3306

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: sudo apt-get update
      - name: install mysql-client
        run: sudo apt-get install -y mysql-client
      - name: Check
        run: mysql -hmysql -P3306 -uroot -pmysql

#   maven-test-job:
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up JDK 8
#       uses: actions/setup-java@v2
#       with:
#         java-version: '8'
#         distribution: 'adopt'
#         cache: maven
#     - name: Test with Maven
#       run: mvn clean test -Dtest=com.jd.jdbc.cache.LRUCacheTest
