# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  services-test-job:
    # 宿主机容器
    runs-on: ubuntu-20.04
    # job运行所在的容器. 不写这一条, job就会在宿主机容器上跑, 实测apt install会有依赖问题
    container: ubuntu:20.04
    services:
      mysql5719:
        # mysql服务容器使用的镜像
        image: mysql:5.7.19
        env:
          MYSQL_ROOT_PASSWORD: mysql
        # 在容器里跑job就不需要端口映射了
#         ports:
#           # Opens tcp port 3306 on the host and service container
#           - 3306:3306

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: apt update
      - name: install mysql-client
        run: apt install -y mysql-client
      - name: Check
        run: mysql -hmysql5719 -P3306 -uroot -pmysql

#   maven-test-job:
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up JDK 8
#       uses: actions/setup-java@v2
#       with:
#         java-version: '8'
#         distribution: 'adopt'
#         cache: maven
#     - name: Test with Maven
#       run: mvn clean test -Dtest=com.jd.jdbc.cache.LRUCacheTest
